# Generated by Django 3.2.15 on 2022-10-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Consorcio')),
            ],
            options={
                'verbose_name': 'Consorcio',
                'verbose_name_plural': 'Consorcios',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Sector')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.consorcio', verbose_name='consorcio')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
    ]
