# Generated by Django 3.2.15 on 2022-10-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='time_prox_visita',
            field=models.IntegerField(default=1, verbose_name='Proxima Visita en Días'),
        ),
    ]
