# Generated by Django 3.2.15 on 2022-10-31 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_auto_20221030_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, choices=[('S', 'SI'), ('N', 'NO')], max_length=2, null=True, verbose_name='Respuesta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.pregunta', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
