# Generated by Django 3.2.15 on 2022-10-31 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.CreateModel(
            name='ImagenRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/img-respuesta', verbose_name='Imagen')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.respuesta', verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'Imagen Respuesta',
                'verbose_name_plural': 'Imagenes respuestas',
            },
        ),
    ]
